import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className = "nav">
          <img src = "https://pngimg.com/uploads/pokemon/pokemon_PNG14.png" className = "nav-brand" alt = "Something went wrong"/>
          <div className = "nav-item-grp">
            <Link href= "/" className = "nav-item">Home</Link>
            <Link href = "/api" className = "nav-item">Signin</Link>
            <a href = "#" className = "nav-item">Signup</a>
          </div>
        </nav>
        {children}
        </body>
    </html>
  );
}
