import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Theme from "./theme";
import SessionProvider from "./SessionProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <SessionProvider>
        <Theme children = {children}/>
      </SessionProvider>
  );
}
